### ISSUE TITLE
Empty playlist button?

### ISSUE THREAD

**Issue by Remco32** [bburky/playnite-playlist#5]
It would be great to be able to quickly empty the playlist. I use playlist to make a list of games I want to play in a session, so quickly cleaning out an old list would be terrific.

**Comment by bburky** [comment]
I'm not quite sure this is needed. In recent versions of the extension I've made sure that it's possible to use most standard keyboard selection shortcuts to manipulate the playlist. You should be able to do a select all (<kbd>Ctrl</kbd> + <kbd>A</kbd>) followed by a delete (<kbd>Delete</kbd> key) to clear the entire playlist.

Do you think a dedicated button is needed for this? The main Playnite UI works the same way and supports the same shortcuts too, I didn't think a button was needed.

**Comment by Remco32** [comment]
Maybe it's my skin (Helium Enhanced Grid) but those shortcuts aren't doing anything for me. They do work in the library view though.

If it can be done with simple keyboard shortcuts then I don't necessarily require a button for it, but for others it might be a more intuitive option.

**Comment by bburky** [comment]
You do need to focus the playlist by clicking on one item in the list before using the shortcuts.


Click on anything in the list. Ctrl-A. Delete.

**Comment by Remco32** [comment]
Turns out that was it. A game will appear already selected though, when switching back to the Playlist tab. Reselecting something again enables the shortcuts again.

**Comment by bburky** [comment]
Yes, I'll try to improve the focus handling issue (requiring a click). I think the current behavior is standard WPF though, and I think the main Playnite library view behaves the same.

I'll see what I can do to improve this, but I'm going to close this ticket for now. I'll also see if I can document the Ctrl-A shortcut somehow.
